-- Crear base de datos dbCursos
CREATE DATABASE IF NOT EXISTS dbCurso
DEFAULT CHARACTER SET utf8;

-- Poner en uso
USE dbCurso;

-- Crear la tabla PERSONA
CREATE TABLE PERSONA 
(
    DNIPER CHAR(8),
    NOMPERS VARCHAR(50) NOT NULL,
    NOMPER VARCHAR(80) NOT NULL,
    FECNACPER date NOT NULL,
    CELPER CHAR(9),
    EMAPER VARCHAR(100),
    SEXPER CHAR(1) NOT NULL,
    TIPPER CHAR(3) NOT NULL,
    DISTPER VARCHAR(80) NOT NULL,
    FECREGPER timestamp,
    PWSPER VARCHAR(20),
    CONSTRAINT DNIPER_PK PRIMARY KEY(DNIPER)
);

-- Crear tabla DEPARTAMENTO
CREATE TABLE DEPARTAMENTO
(
	IDDEP INT,
    NOMDEP VARCHAR(50) NOT NULL,
    DNIPER CHAR(8),
    SALJEFDEP DECIMAL(8,2),
    CONSTRAINT IDDEP_PK PRIMARY KEY(IDDEP)
);

-- Crear tabla EMPLEADO
CREATE TABLE EMPLEADO
(
	IDEMP INT,
    DNIPER CHAR(8),
    FECINGEMP date NOT NULL,
    CARGEMP VARCHAR(40) NOT NULL,
    SALEMP DECIMAL(6,2) NOT NULL,
    IDDEP INT,
    CONSTRAINT IDEMP_PK PRIMARY KEY(IDEMP)
);

-- Crear tabla HISTORICO


-- Relacionar la tabla PERSONA con DEPARTAMENTO
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PERSONA_DEPARTAMENTO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);