-- Eliminar la base de dato dbCurso
DROP DATABASE dbCurso;

-- Crear base de datos dbCursos
CREATE DATABASE IF NOT EXISTS dbCurso
DEFAULT CHARACTER SET utf8;

-- Poner en uso
USE dbCurso;

-- Crear la tabla PERSONA
CREATE TABLE PERSONA 
(
    DNIPER CHAR(8),
    NOMPERS VARCHAR(50) NOT NULL,
    NOMPER VARCHAR(80) NOT NULL,
    FECNACPER date NOT NULL,
    CELPER CHAR(9),
    EMAPER VARCHAR(100),
    SEXPER CHAR(1) NOT NULL,
    TIPPER CHAR(3) NOT NULL,
    DISTPER VARCHAR(80) NOT NULL,
    FECREGPER timestamp,
    PWSPER VARCHAR(20),
    CONSTRAINT DNIPER_PK PRIMARY KEY(DNIPER)
);

-- Crear tabla DEPARTAMENTO
CREATE TABLE DEPARTAMENTO
(
	IDDEP INT,
    NOMDEP VARCHAR(50) NOT NULL,
    DNIPER CHAR(8),
    SALJEFDEP DECIMAL(8,2),
    CONSTRAINT IDDEP_PK PRIMARY KEY(IDDEP)
);

-- Crear tabla EMPLEADO
CREATE TABLE EMPLEADO
(
	IDEMP INT,
    DNIPER CHAR(8),
    FECINGEMP date NOT NULL,
    CARGEMP VARCHAR(40) NOT NULL,
    SALEMP DECIMAL(6,2) NOT NULL,
    IDDEP INT,
    ESTEMP CHAR(1),
    CONSTRAINT IDEMP_PK PRIMARY KEY(IDEMP)
);

-- Crear tabla HISTORICO
CREATE TABLE HISTORICO
(
	IDHIS INT,
    DNIPER CHAR(8),
    FECFINHIST date NOT NULL,
    TIPHIS CHAR(3) NOT NULL,
    COMEHIST VARCHAR(100),
    CONSTRAINT IDHIS_PK PRIMARY KEY(IDHIS)
);

-- Crear tabla INSCRIPCION
CREATE TABLE INSCRIPCION
(
	IDINSC INT,
    DNIPER CHAR(8),
    IDEMP INT,
    IDOFER INT,
    FECINS DATE NOT NULL,
    EVALINSC INT,
    CONSTRAINT IDINSC_PK PRIMARY KEY(IDINSC)
);

-- Crear tabla OFERTA
CREATE TABLE OFERTA
(
	IDOFER INT,
    CODCUR CHAR(3),
    FECOFER DATE NOT NULL,
    FECINICCUROFER DATE NOT NULL,
    IDEMP INT,
    CONSTRAINT IDOFER_PK PRIMARY KEY(IDOFER)
);

-- Crear tabla CURSO
CREATE TABLE CURSO
(
	CODCUR CHAR(3),
    DESCUR VARCHAR(30) NOT NULL,
    CATCUR CHAR(3) NOT NULL,
    DURCUR INT NOT NULL,
    CONSTRAINT CODCUR_PK PRIMARY KEY(CODCUR)
);

-- Relacionar la tabla PERSONA con DEPARTAMENTO
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PERSONA_DEPARTAMENTO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla PERSONA con HISTORICO
ALTER TABLE HISTORICO
ADD CONSTRAINT PERSONA_HISTORICO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla PERSONA con EMPLEADO
ALTER TABLE EMPLEADO
ADD CONSTRAINT PERSONA_EMPLEADO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla PERSONA con INSCRIPCION
ALTER TABLE INSCRIPCION
ADD CONSTRAINT PERSONA_INSCRIPCION_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla EMPLEADO con INSCRIPCION
ALTER TABLE INSCRIPCION
ADD CONSTRAINT EMPLEADO_INSCRIPCION_IDEMP
FOREIGN KEY (IDEMP) REFERENCES EMPLEADO (IDEMP);

-- Relacionar la tabla EMPLEADO con OFERTA
ALTER TABLE OFERTA
ADD CONSTRAINT EMPLEADO_OFERTA_IDEMP
FOREIGN KEY (IDEMP) REFERENCES EMPLEADO (IDEMP);

-- Relacionar la tabla CURSO con OFERTA
ALTER TABLE OFERTA
ADD CONSTRAINT CURSO_OFERTA_CODCUR
FOREIGN KEY (CODCUR) REFERENCES CURSO (CODCUR);

-- Relacionar la tabla OFERTA con INSCRIPCION
ALTER TABLE INSCRIPCION
ADD CONSTRAINT OFERTA_INSCRIPCION_IDOFER
FOREIGN KEY (IDOFER) REFERENCES OFERTA (IDOFER);

-- Relacionar la tabla DEPARTAMENTO con EMPLEADO
ALTER TABLE EMPLEADO
ADD CONSTRAINT DEPARTAMENTO_EMPLEADO_IDDEP
FOREIGN KEY (IDDEP) REFERENCES DEPARTAMENTO (IDDEP);